################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\IPAddress.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Print.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Reset.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\SERCOM.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Stream.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Tone.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Uart.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\WMath.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\WString.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\abi.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\main.cpp \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\new.cpp 

S_UPPER_SRCS += \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\pulse_asm.S 

C_SRCS += \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\WInterrupts.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\cortex_handlers.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\delay.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\hooks.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\itoa.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\math_helper.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\pulse.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\startup.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_analog.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_digital.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_private.c \
C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_shift.c 

C_DEPS += \
.\core\core\WInterrupts.c.d \
.\core\core\cortex_handlers.c.d \
.\core\core\delay.c.d \
.\core\core\hooks.c.d \
.\core\core\itoa.c.d \
.\core\core\math_helper.c.d \
.\core\core\pulse.c.d \
.\core\core\startup.c.d \
.\core\core\wiring.c.d \
.\core\core\wiring_analog.c.d \
.\core\core\wiring_digital.c.d \
.\core\core\wiring_private.c.d \
.\core\core\wiring_shift.c.d 

AR_OBJ += \
.\core\core\IPAddress.cpp.o \
.\core\core\Print.cpp.o \
.\core\core\Reset.cpp.o \
.\core\core\SERCOM.cpp.o \
.\core\core\Stream.cpp.o \
.\core\core\Tone.cpp.o \
.\core\core\Uart.cpp.o \
.\core\core\WInterrupts.c.o \
.\core\core\WMath.cpp.o \
.\core\core\WString.cpp.o \
.\core\core\abi.cpp.o \
.\core\core\cortex_handlers.c.o \
.\core\core\delay.c.o \
.\core\core\hooks.c.o \
.\core\core\itoa.c.o \
.\core\core\main.cpp.o \
.\core\core\math_helper.c.o \
.\core\core\new.cpp.o \
.\core\core\pulse.c.o \
.\core\core\pulse_asm.S.o \
.\core\core\startup.c.o \
.\core\core\wiring.c.o \
.\core\core\wiring_analog.c.o \
.\core\core\wiring_digital.c.o \
.\core\core\wiring_private.c.o \
.\core\core\wiring_shift.c.o 

S_UPPER_DEPS += \
.\core\core\pulse_asm.S.d 

CPP_DEPS += \
.\core\core\IPAddress.cpp.d \
.\core\core\Print.cpp.d \
.\core\core\Reset.cpp.d \
.\core\core\SERCOM.cpp.d \
.\core\core\Stream.cpp.d \
.\core\core\Tone.cpp.d \
.\core\core\Uart.cpp.d \
.\core\core\WMath.cpp.d \
.\core\core\WString.cpp.d \
.\core\core\abi.cpp.d \
.\core\core\main.cpp.d \
.\core\core\new.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
core\core\IPAddress.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\IPAddress.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Print.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Print.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Reset.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Reset.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\SERCOM.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\SERCOM.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Stream.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Stream.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Tone.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Tone.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Uart.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\Uart.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\WInterrupts.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\WInterrupts.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\WMath.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\WMath.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\WString.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\WString.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\abi.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\abi.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\cortex_handlers.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\cortex_handlers.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\delay.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\delay.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\hooks.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\hooks.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\itoa.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\itoa.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\main.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\main.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\math_helper.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\math_helper.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\new.cpp.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\new.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE  -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\pulse.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\pulse.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\pulse_asm.S.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\pulse_asm.S
	@echo 'Building file: $<'
	@echo 'Starting S compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -c -g -x assembler-with-cpp -MMD -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)"  "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\startup.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\startup.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_analog.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_analog.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_digital.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_digital.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_private.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_private.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_shift.c.o: C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino\wiring_shift.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\sloeber\arduinoPlugin\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -D__SKETCH_NAME__="""Samd51_DmaTest""" -DF_CPU=120000000L -DARDUINO=10802 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD  -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\""   "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore" "-IC:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE   -Os  -DVARIANT_QSPI_BAUD_DEFAULT=50000000 "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\sloeber\arduinoPlugin\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/"   -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\adafruit\hardware\samd\1.5.14\variants\metro_m4" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\SPI" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA\utility" -I"C:\Users\Scott\Documents\My Projects\Arduino\Cores\Adafruit ArduinoCore-samd\libraries\Adafruit_ZeroDMA" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '


